// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messagecmd.proto

package net.fengyu.protocol.protobuf;

public final class MessageCmd {
  private MessageCmd() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code protocol.protobuf.CmdID}
   */
  public enum CmdID
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *未使用的命令号，proto3要求枚举第一个元素从0开始，用于默认的消息处理Handler
     * </pre>
     *
     * <code>CMD_ID_DEFAULT = 0;</code>
     */
    CMD_ID_DEFAULT(0),
    /**
     * <pre>
     *连接，完成秘钥交换等
     * </pre>
     *
     * <code>CMD_ID_CONNECT = 1;</code>
     */
    CMD_ID_CONNECT(1),
    /**
     * <pre>
     *登录
     * </pre>
     *
     * <code>CMD_ID_AUTH = 3;</code>
     */
    CMD_ID_AUTH(3),
    /**
     * <pre>
     *登出
     * </pre>
     *
     * <code>CMD_ID_LOGOUT = 4;</code>
     */
    CMD_ID_LOGOUT(4),
    /**
     * <pre>
     *踢人
     * </pre>
     *
     * <code>CMD_ID_KICKOUT = 5;</code>
     */
    CMD_ID_KICKOUT(5),
    /**
     * <pre>
     *心跳
     * </pre>
     *
     * <code>CMD_ID_KEEPALIVE = 6;</code>
     */
    CMD_ID_KEEPALIVE(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *未使用的命令号，proto3要求枚举第一个元素从0开始，用于默认的消息处理Handler
     * </pre>
     *
     * <code>CMD_ID_DEFAULT = 0;</code>
     */
    public static final int CMD_ID_DEFAULT_VALUE = 0;
    /**
     * <pre>
     *连接，完成秘钥交换等
     * </pre>
     *
     * <code>CMD_ID_CONNECT = 1;</code>
     */
    public static final int CMD_ID_CONNECT_VALUE = 1;
    /**
     * <pre>
     *登录
     * </pre>
     *
     * <code>CMD_ID_AUTH = 3;</code>
     */
    public static final int CMD_ID_AUTH_VALUE = 3;
    /**
     * <pre>
     *登出
     * </pre>
     *
     * <code>CMD_ID_LOGOUT = 4;</code>
     */
    public static final int CMD_ID_LOGOUT_VALUE = 4;
    /**
     * <pre>
     *踢人
     * </pre>
     *
     * <code>CMD_ID_KICKOUT = 5;</code>
     */
    public static final int CMD_ID_KICKOUT_VALUE = 5;
    /**
     * <pre>
     *心跳
     * </pre>
     *
     * <code>CMD_ID_KEEPALIVE = 6;</code>
     */
    public static final int CMD_ID_KEEPALIVE_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CmdID valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CmdID forNumber(int value) {
      switch (value) {
        case 0: return CMD_ID_DEFAULT;
        case 1: return CMD_ID_CONNECT;
        case 3: return CMD_ID_AUTH;
        case 4: return CMD_ID_LOGOUT;
        case 5: return CMD_ID_KICKOUT;
        case 6: return CMD_ID_KEEPALIVE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CmdID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CmdID> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CmdID>() {
            public CmdID findValueByNumber(int number) {
              return CmdID.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return net.fengyu.protocol.protobuf.MessageCmd.getDescriptor().getEnumTypes().get(0);
    }

    private static final CmdID[] VALUES = values();

    public static CmdID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CmdID(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protocol.protobuf.CmdID)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020messagecmd.proto\022\021protocol.protobuf*}\n" +
      "\005CmdID\022\022\n\016CMD_ID_DEFAULT\020\000\022\022\n\016CMD_ID_CON" +
      "NECT\020\001\022\017\n\013CMD_ID_AUTH\020\003\022\021\n\rCMD_ID_LOGOUT" +
      "\020\004\022\022\n\016CMD_ID_KICKOUT\020\005\022\024\n\020CMD_ID_KEEPALI" +
      "VE\020\006B*\n\034net.fengyu.protocol.protobufB\nMe" +
      "ssageCmdb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
